using CobolToQuarkusMigration.Discovery.Models;
using CobolToQuarkusMigration.Discovery.Roles;
using FluentAssertions;
using Xunit;

namespace CobolToQuarkusMigration.Tests.Discovery;

public sealed class ArtifactRoleClassifierTests
{
    private static RoleClassification ClassifySingle(string path, string text)
    {
        var results = ArtifactRoleClassifier.ClassifyProject(new[] { new ClassifierSourceFile(path, text) });
        results.Should().ContainSingle();
        return results[0];
    }

    [Theory]
    [InlineData("bin/Debug/net10.0/Foo.cs")]
    [InlineData("Project/obj/Release/Generated.cs")]
    [InlineData("a/b/obj/x.cs")]
    public void IsExcludedBuildOutputPath_MatchesBinOrObjSegments(string path)
    {
        ArtifactRoleClassifier.IsExcludedBuildOutputPath(path).Should().BeTrue();
    }

    [Fact]
    public void IsExcludedBuildOutputPath_DoesNotMatchOrdinarySource()
    {
        ArtifactRoleClassifier.IsExcludedBuildOutputPath("Repositories/EmployeeRepository.cs").Should().BeFalse();
    }

    [Fact]
    public void ClassifyProject_ExcludesBinObjFilesFromResults()
    {
        var files = new[]
        {
            new ClassifierSourceFile("bin/Debug/Foo.cs", "public class Foo { public void Do() { } }"),
            new ClassifierSourceFile("src/Bar.cs", "public class Bar { public void Do() { System.Console.WriteLine(1); } }"),
        };

        var results = ArtifactRoleClassifier.ClassifyProject(files);

        results.Should().ContainSingle(r => r.SymbolLocator.Contains("Bar"));
        results.Should().NotContain(r => r.SymbolLocator.Contains("Foo"));
    }

    [Fact]
    public void ClassifyType_DbContextSubclass_IsClassifiedPersistence()
    {
        var text = @"
using Microsoft.EntityFrameworkCore;
namespace App.Data;
public class ApplicationContext : DbContext
{
    public DbSet<int> Numbers { get; set; }
}";
        var result = ClassifySingle("Data/ApplicationContext.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.Persistence);
        result.Citations.Should().Contain(c => c.RuleName.Contains("Persistence", StringComparison.OrdinalIgnoreCase) || c.Excerpt.Contains("DbContext"));
    }

    [Fact]
    public void ClassifyType_EfMigration_IsClassifiedGeneratedAndPersistence()
    {
        var text = @"
using Microsoft.EntityFrameworkCore.Migrations;
namespace App.Migrations;
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) { }
}";
        var result = ClassifySingle("Data/Migrations/20240101_InitialCreate.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.Generated);
        result.Roles.Should().Contain(ArtifactRoleTag.Persistence);
    }

    [Fact]
    public void ClassifyType_AutoGeneratedComment_IsClassifiedGenerated()
    {
        var text = @"
// <auto-generated />
namespace App;
public class Widget
{
    public void Compute() { var x = 1; }
}";
        var result = ClassifySingle("Generated/Widget.cs", text);

        result.Roles.Should().ContainSingle().Which.Should().Be(ArtifactRoleTag.Generated);
        result.RequiresReview.Should().BeFalse();
    }

    [Theory]
    [InlineData("[Fact]")]
    [InlineData("[Theory]")]
    [InlineData("[TestMethod]")]
    public void ClassifyType_XunitOrMsTestAttribute_IsClassifiedTest(string attribute)
    {
        var text = $@"
namespace App.Tests;
public class SomeTests
{{
    {attribute}
    public void ItWorks() {{ }}
}}";
        var result = ClassifySingle("Tests/SomeTests.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.Test);
    }

    [Fact]
    public void ClassifyType_PathUnderTestsFolder_IsClassifiedTest()
    {
        var text = "namespace App; public class Helper { public void Do() { } }";
        var result = ClassifySingle("MyProject.Tests/Helper.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.Test);
    }

    [Fact]
    public void ClassifyType_DependencyInjectionRegistrations_AreClassifiedCompositionDI()
    {
        var text = @"
namespace App;
public class Startup
{
    public void ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddScoped<IFoo, Foo>();
        services.AddSingleton<IBar, Bar>();
    }
}";
        var result = ClassifySingle("Startup.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.CompositionDI);
    }

    [Fact]
    public void ClassifyType_MiddlewareInterfaceImplementation_IsClassifiedMiddleware()
    {
        var text = @"
namespace App;
public class LoggingMiddleware : Microsoft.AspNetCore.Http.IMiddleware
{
    public System.Threading.Tasks.Task InvokeAsync(Microsoft.AspNetCore.Http.HttpContext context, Microsoft.AspNetCore.Http.RequestDelegate next) => next(context);
}";
        var result = ClassifySingle("Middleware/LoggingMiddleware.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.Middleware);
    }

    [Fact]
    public void ClassifyType_ApiControllerAttribute_IsClassifiedFrameworkAdapter()
    {
        var text = @"
namespace App.Controllers;
[Microsoft.AspNetCore.Mvc.ApiController]
[Microsoft.AspNetCore.Mvc.Route(""api/[controller]"")]
public class EmployeesController : Microsoft.AspNetCore.Mvc.ControllerBase
{
    [Microsoft.AspNetCore.Mvc.HttpGet]
    public string Get() => ""ok"";
}";
        var result = ClassifySingle("Controllers/EmployeesController.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.FrameworkAdapter);
    }

    [Fact]
    public void ClassifyType_HttpClientNamedGateway_IsClassifiedIntegrationAdapter()
    {
        var text = @"
using System.Net.Http;
namespace App.Integrations;
public class PayrollGateway
{
    private readonly HttpClient _client = new HttpClient();
    public void Send() { _client.GetAsync(""http://example""); }
}";
        var result = ClassifySingle("Integrations/PayrollGateway.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.IntegrationAdapter);
    }

    [Fact]
    public void ClassifyType_PlainClassWithExecutableMembersAndNoOtherSignals_FallsBackToBusiness()
    {
        var text = @"
namespace App.Domain;
public class LeaveRequestCalculator
{
    public int CalculateRemainingDays(int total, int used)
    {
        return total - used;
    }
}";
        var result = ClassifySingle("Domain/LeaveRequestCalculator.cs", text);

        result.Roles.Should().ContainSingle().Which.Should().Be(ArtifactRoleTag.Business);
        result.RequiresReview.Should().BeFalse();
        result.Confidence.Should().BeGreaterThan(0.5);
    }

    [Fact]
    public void ClassifyType_InterfaceWithNoExecutableMembers_IsClassifiedUnknownAndRequiresReview()
    {
        var text = @"
namespace App.Interfaces;
public interface IEmployeeRepository
{
    System.Threading.Tasks.Task<int> GetCountAsync();
}";
        var result = ClassifySingle("Interfaces/IEmployeeRepository.cs", text);

        result.Roles.Should().ContainSingle().Which.Should().Be(ArtifactRoleTag.Unknown);
        result.RequiresReview.Should().BeTrue();
        result.Confidence.Should().BeLessThan(0.5);
    }

    [Fact]
    public void ClassifyType_MultipleDistinctNonBusinessSignals_RequiresReview_NoInventedPrimaryRole()
    {
        // A type that is simultaneously an EF Core mapped entity AND registers services in the
        // DI container mixes two distinct non-business technical signals. The classifier must
        // record both tags and flag for review rather than picking one as "the" role.
        var text = @"
using Microsoft.EntityFrameworkCore;
namespace App.Domain;
[Table(""Employees"")]
public class Employee
{
    public void ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddScoped<IFoo, Foo>();
    }
}";
        var result = ClassifySingle("Domain/Employee.cs", text);

        result.Roles.Should().Contain(ArtifactRoleTag.Persistence);
        result.Roles.Should().Contain(ArtifactRoleTag.CompositionDI);
        result.Roles.Should().NotContain(ArtifactRoleTag.Business);
        result.RequiresReview.Should().BeTrue();
    }

    [Fact]
    public void ClassifyProject_CsprojFile_IsClassifiedBuildTooling()
    {
        var text = "<Project Sdk=\"Microsoft.NET.Sdk\"></Project>";
        var result = ClassifySingle("App.csproj", text);

        result.Roles.Should().ContainSingle().Which.Should().Be(ArtifactRoleTag.BuildTooling);
        result.RequiresReview.Should().BeFalse();
    }

    [Fact]
    public void Classify_AllResults_IncludeClassificationRuleAndCitations()
    {
        var text = "namespace App; public class Foo { public void Do() { var x = 1; } }";
        var result = ClassifySingle("Foo.cs", text);

        result.ClassificationRule.Should().NotBeNullOrWhiteSpace();
        result.Citations.Should().NotBeEmpty();
        result.Citations.Should().OnlyContain(c => !string.IsNullOrWhiteSpace(c.Locator) && !string.IsNullOrWhiteSpace(c.RuleName));
    }
}
